export const ACTIONS = Object.freeze({
  SET_ACTIVE_GROUP: 'SET_ACTIVE_GROUP',
  ADD_GROUP       : 'ADD_GROUP',
  ARCHIVE_GROUP   : 'ARCHIVE_GROUP',
  ADD_WORKOUT     : 'ADD_WORKOUT',
  REMOVE_WORKOUT  : 'REMOVE_WORKOUT',
  ADD_EXERCISE    : 'ADD_EXERCISE',
  REMOVE_EXERCISE : 'REMOVE_EXERCISE',
})
