#!/usr/bin/env python
import os
from sys import exit
from subprocess import check_call

print "\nStarting Web compilation process"
print   "================================"

dev_null = open('/dev/null', 'w')
def minify(file):
	print "  > Minifying "+file.rpartition('/')[2]
	check_call(node+'minify '+file+' '+file, shell=True, stdout=dev_null, stderr=dev_null)

# root     = os.path.dirname(os.path.abspath(__file__))+'/'
root     = ''
node     = root+'node_modules/.bin/'
root_js  = root+'src/js/'
build_js = root+'build/src/js/'

html       = root_js+'index.html'
libs       = [root_js+'libs/minified.js']
js         = build_js+'script.js'
css        = build_js+'styles.css'
final_path = build_js+'complete.html'

# Compiling CoffeeScript and Less
print "==> Brewing CoffeeScripts"
check_call(node+'coffee --no-header -bc -o '+build_js+' '+root_js, shell=True)
check_call('cp '+root_js+'libs/bugsense.min.js '+build_js+'bugsense.min.js', shell=True)
minify(js)
print "==> Shortening CSS's"
check_call(node+'lessc '+root_js+'/less/styles.less '+css, shell=True)
print "  > Removing unused rules"
check_call(node+'uncss -s ../../'+css+' '+html+' > '+css+'.tmp && mv '+css+'.tmp '+css, shell=True)
print "  > Prefixing needed rules"
check_call(node+'autoprefixer -b "last 2 iOS versions, Android 4.1" -o '+css+'.tmp '+css+' && mv '+css+'.tmp '+css, shell=True)
minify(css)

# Merges CSS and JS into the HTML file
print "==> Compiling everything into the HTML file"
final_file = open(final_path, 'w')

for line in open(html):
	if 'HERE BE CSS' in line:
		final_file.write(open(css).read())
	elif 'HERE BE JS' in line:
		for lib in libs:
                    final_file.write(open(lib).read())
		final_file.write(open(js).read())
	else:
		final_file.write(line)

final_file.close()
minify(final_path)
final_file = open(final_path)

# Bundling that HTML into the main PebbleKit JS File
print "==> Bundling HTML code into the PebbleKit JS file"
pebblekit_path = build_js+'pebble-js-app.js'
pebblekit_file = open(pebblekit_path, 'w')
pebblekit_file.write("config_html = "+repr(final_file.read())+";\n")
pebblekit_file.write(open(build_js+'pebble-integration.js').read())
pebblekit_file.close()
minify(pebblekit_path)

final_size = os.path.getsize(pebblekit_path)
print "  > Final file size: %.2fKb" % (final_size / 1024.0)

print "================================"
print "====> Web compilation done, sir!\n"
exit(0)