export const ACTIONS = Object.freeze({
  ADD_GROUP      : 'ADD_GROUP',
  ARCHIVE_GROUP  : 'ARCHIVE_GROUP',
  ADD_WORKOUT    : 'ADD_WORKOUT',
  REMOVE_WORKOUT : 'REMOVE_WORKOUT',
  ADD_EXERCISE   : 'ADD_EXERCISE',
  REMOVE_EXERCISE: 'REMOVE_EXERCISE',
})