#include "defs.h"

int icon_ids[] = { RESOURCE_ID_ICON_WORKOUT_A, RESOURCE_ID_ICON_WORKOUT_B,
    RESOURCE_ID_ICON_WORKOUT_C, RESOURCE_ID_ICON_WORKOUT_D, RESOURCE_ID_ICON_WORKOUT_E,
    RESOURCE_ID_ICON_WORKOUT_F, RESOURCE_ID_ICON_WORKOUT_G
};